### ISSUE TITLE
Crash - Exc bad access code 1

### ISSUE THREAD

**Issue by peterschmiz** [ProjectSeptemberInc/gl-react-native#102]
I have an issue, which I'm not sure how to solve.
What I want to achieve is to scale up the whole Surface in my component.
(zooming in)

I have to scale the Surface, because I put together a composition of multiple images and effects there and I need at least 2x zoom (i was thinking how to 'zoom in' and not scaling the Surface, but had no good solution).

My app is crashing with 'exc bad access code 1', in GLCanvas->drawRect:
`NSError *error;
   BOOL syncSuccessful = [self syncData:&error];`

I could not reproduce it every time, in release version i was only able to reproduce it like 3-4 times out of 30, in debug mode is more often and especially having the Live Reload enabled my app crashes, so I have to re-run the project in XCode.

The zoom is done by setting the surface WIDTH / HEIGHT from state and repositioning it to be at the center of my view.

`width={WINDOW_WIDTH * this.state.zoom}
height={WINDOW_HEIGHT * this.state.zoom}`

I use AnimatedSurface and have multiple images passed as uniforms to my shader. I'm not sure about that, but maybe using big (960x1704) images can cause this or maybe my shader fails, I'm not sure.

Could you please help me or check the cause or if you have an idea, how to solve the zooming.
Right now my solution is working very well, except the random crashing :)

**Comment by peterschmiz** [comment]
Update: not true :( I was able to crash it again.

Just one more note, which I noticed just now: if autoRedraw is enabled it works, no crash, still, using autoRedraw is too heavy for in case :(

**Comment by gre** [comment]
do you need the user to be able to change the zoom in real time (it's in a ScrollView?) or is it a static zoom?
Because if it's a static zoom, you might just crop your image before? (either programmatically or with a shader)

also, do you have a minimal example that reproduce the crash? i'll need to investigate, there might be another race condition or a memory pb in some case

**Comment by gre** [comment]
BTW we have experienced this error sometimes, but it was always happening in DEV mode, we have never seen it happening in Release mode though.
Have you tried to run in Release mode, does it ever happen there?

I don't really understand the error.. it looks like it crashes in drawRect when accessing self. we are not calling drawRect directly, it's the ios glkview thing.. so I'm not sure how to fix it.
or maybe the stacktrace is totally wrong and it actually fails somewhere else in syncData..

It sounds like the bug is a race condition that happen when you use the RN Refresh (e.g. on simulator): some objects get deallocated but the drawRect is still called..

**Comment by peterschmiz** [comment]
Hi, sorry for the late response. Its working in release mode and also you are right: it happens all the time when I use RN live reload... so now I reload it manually and everything works!
I think this ticket can be closed now, because its more like an RN issue to me :)

**Comment by gre** [comment]
yeah, it's tricky. it might be an edge case that no one see yet because RN people don't use GLKView that much :)

**Comment by gre** [comment]
thanks for help on investigating :)
