### ISSUE TITLE
Can't resize framebuffer

### ISSUE THREAD

**Issue by sscaff1** [ProjectSeptemberInc/gl-react-native#104]
What causes this error? Forgive me my Objective C and Java isn't very good. I think it has something to do the image size, but I'm not 100% sure. 

![simulator screen shot aug 22 2016 5 47 30 pm](https://cloud.githubusercontent.com/assets/1554424/17876604/880d670e-6890-11e6-80f8-7b86c02f3dbf.png)

**Comment by gre** [comment]
either you have negative width/height OR you have reach limits of the width/height max framebuffer size (on a GL.Node / Surface) which is set in `GL_MAX_RENDERBUFFER_SIZE` (depends on device)

**Comment by gre** [comment]
should provide more explicit error message :+1:

**Comment by sscaff1** [comment]
Sorry about that. It turned out to be first one. Thank you for the help. Is there a way to know what the GL_MAX_RENDERBUFFER_SIZE is for each device?

**Comment by gre** [comment]
you can ask gl via a native call, or just go to http://webglreport.com/ on your mobile browser (because I'm pretty sure WebGL will have these same limits).

there must be someone on the internet that have listed them all though. But best is to use the value programmatically, which makes me thing gl-react should expose some of these ( https://github.com/ProjectSeptemberInc/gl-react/issues/66 )
