### ISSUE TITLE
Texture 90 degree rotation (without vertex shaders)

### ISSUE THREAD

**Issue by jasongaare** [ProjectSeptemberInc/gl-react-native#107]
Here is my situation: I am passing an image URL into a fragment shader, and if the photo is a landscape photo (width > height) I would like to rotate the image. From my understanding by reading through the issues, there is not currently an implementation of vertex shaders nor a plan to implement them ([#6](https://github.com/ProjectSeptemberInc/gl-react/issues/6)) 

I found [this stackoverflow question](http://stackoverflow.com/questions/28074977/rotating-a-texture-on-a-fragment-shader-in-glsl-es) that address my needs, but **all of the solutions only seem to work for a square photo** (width = height), the rest distort the photos in an undesirable way. 

I've also noted that there is a thread recommending NOT to use the <Image> component as a child to a <Surface> but rather to pass the image URL directly to the shader for rendering purposes ([#84](https://github.com/ProjectSeptemberInc/gl-react-native/issues/84)). 

So essentially, my issue is finding a the best way to implement this within the bounds of gl-react-native. I'd love to pass a rotated <Image> component into the shader to save the trouble of applying the rotation in the GL component. Or find a way to rotate well. Is there a way to do this effectively? 

I can move this discussion to stackoverflow if that's preferable, I just find this issues thread to be more active with more knowledgable folks. Thanks

**Comment by gre** [comment]
I'm not sure this will help this (yet!) but see https://github.com/gre/gl-react-image that will make sure the image never gets distort (in cover / contain) modes.
that said it doesn't support rotation (but it could be extended to support this).

actually is your rotation a problem that gl-react have an issue using the correct exif orientation  ? because we used to have this problem, we used to fix it, and it looks like it's back in Android :( when testing the example app of gl-react-native.

https://github.com/gre/gl-react-image/issues/1

@dcworldwide: did you had a chance to test on latest react native version? not sure if it's a regression on gl-react side or in RN.

**Comment by st0ffern** [comment]
https://github.com/bamlab/react-native-image-resizer

**Comment by gre** [comment]
solution suggested by @stoffern is actually a good idea too, doing less processing on the GPU but do it statically once (by CPU), can be better if your image doesn't change.
it's a tradeoff.

**Comment by jasongaare** [comment]
I'll give that library a shot, @stoffern.

However, it looks like it is ONLY for local files? My images are from a URL not on the phone.

**Comment by gre** [comment]
does the image display fine on browser but not when injecting in gl-react, it's then rotated ?
if it's this, it's a bug on gl-react side. just to confirm.

**Comment by st0ffern** [comment]
@jasongaare then fetch it to local temp or base64..

**Comment by jasongaare** [comment]
Slightly confused by your question @gre... here are some screenshots of what I'm trying to accomplish if it helps... 

This is the photo
![simulator screen shot sep 1 2016 9 52 08 am](https://cloud.githubusercontent.com/assets/15896334/18172217/394b838e-702a-11e6-8ee5-1c345e48b7d2.png)

then I want to rotate it and apply a shader (which I've turned off the effect for seeing the rotation)
![simulator screen shot sep 1 2016 9 52 27 am](https://cloud.githubusercontent.com/assets/15896334/18172271/6a57e5c6-702a-11e6-8cc6-0b1796c33bf2.png)

as you can see the code is _close_ but not quite there. Here is my shader.

```
  vec2 rotateCoords = uv;
  float sin_factor = sin(-90.0);
  float cos_factor = cos(-90.0);
  rotateCoords = vec2((rotateCoords.x - 0.5) * (renderSize.x / renderSize.y), rotateCoords.y - 0.5);
  rotateCoords *= mat2(cos_factor, sin_factor, -sin_factor, cos_factor);
  rotateCoords += 0.5;

  vec4 image = texture2D(tex, uv);

  // this is a photo with landscape orientation
  if (renderSize.x >= renderSize.y) {
    image = texture2D(tex, rotateCoords);
  }

    gl_FragColor = vec4(image.r, image.g, image.b, 0.5);
  }
```

**Comment by gre** [comment]
ok, don't worry about my question then. I thought you were accidentally getting a rotated image because of gl-react and you wanted to counter rotate to workaround.
so you actually do want the rotation.
you might look at @stoffern idea.

not sure how to easily fix the stretch effect if you try to do it in the GLSL, but it also means cropping the image. and then, there is multiple ways to do (contain, cover, centered? from top, etc..)

**Comment by gre** [comment]
I would suggest:
- rotate the image locally with that lib
- then either:
  - if you then want to use gl-react to do whatever effect, then maybe worth using gl-react-image. to avoid the stretch problem.
  - otherwise if you just want to render the rotated image and that's it, just use a RN Image. that fix the stretch by default (and you can use whatever resizeMode you want)

**Comment by jasongaare** [comment]
Okay, so here is the solution I found. It's not so much a workaround, as it is an alternative approach.

Essentially, since the `<Image>` component in RN has a `{ transform: rotate }` style, it ended up making more sense to:
1.  Utilize the GL shader on the original photo
2. Use `Surface.captureFrame()` to save the altered photo to a temporary location
3. Then use an `<Image>` component to apply the rotation to the new photo

Thanks for all the help guys, marking as closed.
