### ISSUE TITLE
[Android] Image distorted when captured on certain devices

### ISSUE THREAD

**Issue by superandrew213** [ProjectSeptemberInc/gl-react-native#125]
Original Image:
![img_20161115_113623](https://cloud.githubusercontent.com/assets/13059204/20473206/cea4f31e-b00a-11e6-8f43-04ac5a79ee2b.jpg)

Captured Image:
![a096a5ba-dc6d-4fcc-82ed-9a6fef7d9b5e](https://cloud.githubusercontent.com/assets/13059204/20473207/cf71fd5a-b00a-11e6-98f9-5f1768ccc1fe.jpg)

Issue was reported on a Google Pixel phone with Android 7.1. Have tested the issue on sim with Android 7 & 7.1 but could not replicate it.

Not sure whether issue occurs on all devices with Android 7.1 or just the Google Pixel phone. Am not able to test it on a device with Android 7+.

It appears that the image has been sliced diagonally, stretched and stacked.

### Edit:
Devices experiencing this issue:
Google Pixel
Moto G4 Plus
LG V20
Samsung Galaxy A9
Google Nexus 5x
OnePlus 3T

**Comment by gre** [comment]
that's very weird.. have you tried smaller images / other images from other sources? (e.g. try http://i.imgur.com/5EOyTDQ.jpg ) Can you try to run the [example](https://github.com/ProjectSeptemberInc/gl-react-native/tree/master/example) app, see if it repro on every images?




I think there are basically 3 spots to look for this bug:

- [[1]](https://github.com/ProjectSeptemberInc/gl-react-native/blob/9c9696ded461c3872eef62cd2a56829652edb077/android/src/main/java/com/projectseptember/RNGL/GLImage.java#L51-L68) we load image with the FB library http://frescolib.org/ (available through React Native)
- [[2]](https://github.com/ProjectSeptemberInc/gl-react-native/blob/1258934d96af41b184824c27c588a64a5743d661/android/src/main/java/com/projectseptember/RNGL/GLImage.java#L72-L75) we invert the Y axis to normalize it for OpenGL (y axis convention is inverted)
- [[3]](https://github.com/ProjectSeptemberInc/gl-react-native/blob/b5cf9192dad87e2b5a662926d310a24052b5c6a7/android/src/main/java/com/projectseptember/RNGL/GLTexture.java#L66) we directly pass the resulting bitmap to GL


Assuming **[1]** and **[3]** are correct, one spot to look for the bug is the **[2]**, but i'm not seeing anything done wrong. maybe see what it does if you replace that code with with `final Bitmap bitmap = source;` ?

**Comment by superandrew213** [comment]
Unfortunately I don't have the Google Pixel phone anymore and can't test this. I tested it on the sim and could not replicate the issue. I'm not sure weather this is happening only on the Pixel phone or any Android device running Android 7+. It would be great if someone who has the Pixel phone or any device running Android 7 could test this.

I will try to hunt someone down if I can :)

**Comment by superandrew213** [comment]
@gre I was able to try the image you suggested on the Google Pixel phone:

![4e3d3b79-f410-42c5-8f6e-ea5ee6752f1b](https://cloud.githubusercontent.com/assets/13059204/21182529/52191be8-c24f-11e6-8586-09a3b8305de0.jpg)

Haven't tried the example app yet. Do you have any idea why it would only happened on the Google Pixel phone? Could it be the OpenGL ES version?

**Comment by gre** [comment]
that's super weird. basically each new pixel row get offset by 1 pixel to right. mmh. I'm not sure where the bug is.

**Comment by st0ffern** [comment]
This is a epic bug 😆 😟

**Comment by st0ffern** [comment]
@superandrew213 
https://github.com/ProjectSeptemberInc/gl-react-native/blob/master/android/src/main/java/com/projectseptember/RNGL/RNGLContext.java#L23
Try changing this to: "gl_Position = vec4(position,0.0,0.0);"

**Comment by superandrew213** [comment]
sorry @stoffern haven't been able to get access to the Google Pixel phone. When I do, I will report back.

**Comment by gre** [comment]
i think the shader code is correct. but maybe it's the problem at the "capture" time, because you mean the problem only appear when you capture the pixels right?

I think there must be something wrong in that logic: https://github.com/ProjectSeptemberInc/gl-react-native/blob/master/android/src/main/java/com/projectseptember/RNGL/GLCanvas.java#L874-L899

Not sure if we enter in a case that code don't work for Google Pixel device or if it's a bug in the OpenGL driver implementation of that device...

> ah, and also, thanks Google for naming your phone "Pixel", it will really help for googling the bugs \o/ %$%#@

**Comment by superandrew213** [comment]
@gre yes it only appears when you capture. The Google Pixel phone has the Nvidia's OpenGL ES 3.2 driver.

**Comment by superandrew213** [comment]
@gre this issue is also happening on the LG V20

**Comment by superandrew213** [comment]
Also happening on Moto G4 Plus with Android 6 and OpenGL ES 3.1. So Android version doesn't seem to be the problem. I tested it on another device with OpenGL ES 3.1 and it was working fine. So OpenGL version doesn't seem to cause the issue either.

**Comment by superandrew213** [comment]
This seems to be one crazy bug 🤡 It seems to also happen on some Samsung s8 but not on other Samsung s8. Same phone and same Android version. So the phone itself might not be the issue. However it seems to be happening on newer phones/Android versions.

**Comment by superandrew213** [comment]
This issue doesn't happen when user takes photos with an external camera and adds them to their phone.

**Comment by st0ffern** [comment]
@superandrew213 try using latest react-native-camera@1.0.1 and see if it solves the problem

**Comment by superandrew213** [comment]
Seems to be similar to these issues:

https://stackoverflow.com/questions/43768852/passing-srtm-hgt-file-as-texture-to-opengl-shader-results-in-skewed-image

https://stackoverflow.com/questions/13046941/disorted-image-loaded-in-i-o-suspension-mode-with-libjpeg

**Comment by superandrew213** [comment]
Ok, so after 2 years of trying to fix this "user reported" issue (without being able to reproduce it on any  device), it looks like I found a way to "make it work".

In my case the surface was the width of the user's device. So I'm assuming that's what might have caused the issue for some users but not others. Different device widths, yielding different surface widths.

It seems to be related to OpenGL expecting data to be 4-byte aligned (see link above). I'm not sure if the width of an image can affect it's byte alignment.

I tried using `glPixelStorei` to set the pack alignment:
https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glReadPixels.xml
```java
// Set alignment to 1 before calling glReadPixels in createSnapshot
glPixelStorei(GL_PACK_ALIGNMENT, 1);
glReadPixels(x, y, w, h, GL_RGBA, GL_UNSIGNED_BYTE, intBuffer);
```

But that didn't have an effect.

Then randomly I tried making the surface `width` & `height` be divisible by 4.

```js
width={Math.floor(width / 4) * 4}
```

And that "fixed" it.

**Comment by 0plus1** [comment]
Hi @superandrew213 just wanted to thank you for this solution, was banging my head on this one as well. I had the issue on a Nokia 7 phone and I was going insane.

I too was setting the width to the device width.

Should we file this under: "programming is actually just magic"?

**Comment by superandrew213** [comment]
@0plus1 unfortunately it's not fully fixed. It seems to be still happening on some devices. Less than before though 😄.

**Comment by agrawalsurabhi89** [comment]
Any update on this issue??
