### ISSUE TITLE
Value of type NSNumber cannot be converted to NSArray

### ISSUE THREAD

**Issue by jamesarmenta** [ProjectSeptemberInc/gl-react-native#144]
Just following one of the basic tutorials when I get this error:
<img width="342" alt="error" src="https://cloud.githubusercontent.com/assets/7853967/23777241/f17e1cd0-04e7-11e7-9586-b7bef4e02a8b.png">

```
<Surface width={300} height={300}>
   <HueRotate hue={.5}>
      <Image style={{ width: 300, height: 300 }} source={this.state.memoryImage}/>
   </HueRotate>
</Surface>
```
```
const shaders = GL.Shaders.create({
  hueRotate: {
    frag: `
precision highp float;
varying vec2 uv;
uniform sampler2D tex;
uniform float hue;

void main() {
  gl_FragColor = vec4(0,1,0, 1.0);
}
    `
  }
});

module.exports = GL.createComponent(
  ({ hue, children: tex }) =>
  <GL.Node
    shader={shaders.hueRotate}
    uniforms={{ hue, tex }}
  />
, { displayName: "HueRotate" });
```

Any idea why this might be?

**Comment by gre** [comment]
very weird! can you check versions

```
npm ls gl-react gl-react-native
```

**Comment by jamesarmenta** [comment]
Woops, forgot to include that. 
gl-react@2.2.9 
gl-react-native@2.40.2

**Comment by jamesarmenta** [comment]
Any update on this? I would really like to be able to import a random float on each load of the gl-react component.

**Comment by st0ffern** [comment]
@gre you should concider reverting/overreleasing versions that works. and make GL-React v3 as a @next version in NPM..

Just like `Koa` does..

**Comment by gre** [comment]
@jamesarmenta sorry but i'm not actively working on the v2 as i'm focusing on the v3 at the moment (which is more and more ready) , this bug is pretty weird and PR are welcomed to fixing it.

@stoffern I wished NPM would understand that `-alpha` means "it's not the latest" ^^ how does `@next` works, I never heard about it, you can always override a `next` version?

**Comment by st0ffern** [comment]
`npm publish --tag next`

To publish a prerelease without making it installed by default, you should specify a tag other than “latest”. For example, to set the “next” tag:
`npm publish --tag next`

Conveniently, this also allows the latest prerelease to be installed with the tag name instead of specifying an exact version:
npm install package@next

You can also add me as a collaborator so help you out abit with issues, PRs etc 😉 
Altho i cannot help you with CIs and NPM as i dont have the rights there.

**Comment by CubeSugar** [comment]
All uniform var defined in shader must be used.

```
precision highp float;
varying vec2 uv;
uniform sampler2D tex;
uniform float hue;

void main() {

    // do something with hue & tex
    float _hue = hue;
    vec4 _color = texture2D(tex, uv);

    gl_FragColor = vec4(0.0, 1.0, 0.0, 1.0);
}
```

**Comment by jniac** [comment]
same problem here
    "gl-react": "^2.3.1",
    "gl-react-native": "^2.48.0",

![image](https://user-images.githubusercontent.com/11039919/36454104-e13b89b4-169a-11e8-94f2-e67f0c933743.png)
