### ISSUE TITLE
[ASK] How to implement openGL method ? 

### ISSUE THREAD

**Issue by RZulfikri** [ProjectSeptemberInc/gl-react-native#153]
Hi, this is not issue. i just wanna ask. i want to implement image processing using opengl, but i dont know how to implemen gl mehod in this component. the qustion is ,how to implement any gl method, like  glViewport() in this component ? any document or example ? 

thanks.

**Comment by gre** [comment]
it's not possible with gl-react v2. (and won't be fixed in v2)
in gl-react v3 it's possible, especially for React Native you have the EXGLView that you can freely use and have a WebGL Context instance: see https://github.com/gre/gl-react/blob/master/packages/gl-react-native/README.md#vanilla-webgl

v3 is still an alpha but should work.
