### ISSUE TITLE
Image from live camera view is not displayed

### ISSUE THREAD

**Issue by macrostart** [ProjectSeptemberInc/gl-react-native#22]
I'm trying to apply a fragment shader to the live camera view, but I'm getting black pixels.
In my code I've used the [react-native-camera library](https://github.com/lwansbrough/react-native-camera library).

Replacing the camera with a still image works fine. Surprisingly, child components of the camera view are also visible. That is: if I nest a `<Text>hello world</Text` component in the camera view (the library permits this), I can see the text in the GL.View output, surrounded by black pixels.  It seems that pixels taken directly from the camera view are treated as completely black in the GL.View.

Is there a way to apply a fragment shader to the live camera view?

**Comment by gre** [comment]
I guess this is related to https://github.com/ProjectSeptemberInc/gl-react-native/issues/23 too.

Some advanced views when screenshot with the current code unfortunately produce Black rectangle. This is also the case for a GLKView (if you screenshot a gl-react-native view itself, you would also obtain a Black rectangle).

I have not found yet a satisfying solution so if you have an idea I'm happy to accept it, we need to find another way to screenshot these view, and maybe we need to write specific code for these.. because this is also a performance concern ( https://github.com/ProjectSeptemberInc/gl-react-native/issues/6 )

I am wondering if we can "duck type" that a view is of a given kind and then apply specific logic on it, I would like to avoid strongly depending on these libraries.

**Comment by gre** [comment]
a way to solve this is probably to fork react-native-camera and expose in some way the "AVCapture" object so we can use it in GL.. http://stackoverflow.com/questions/24388179/how-to-render-glkviewcontroller-with-iphone-camera

This raise a concern of interoperability. I don't know what's the best way to keep libraries interoperable and not going into a "big lib that do everything...".

More generally, we will need to refactor gl-react-native to allow that and maybe depends on AVFoundation.. A good way could also be to maybe use https://github.com/BradLarson/GPUImage
