### ISSUE TITLE
Documentation at gitbook not accessible (404)

### ISSUE THREAD

**Issue by macrostart** [ProjectSeptemberInc/gl-react-native#39]
The link to gitbook docs: 

```
http://projectseptemberinc.gitbooks.io/gl-react/content/
```

results in 404. Since gl-react and gl-react-native share the url, this affects both repositories.

<img width="732" alt="screen shot 2015-12-03 at 11 21 47" src="https://cloud.githubusercontent.com/assets/15048404/11558152/360b7666-99b1-11e5-8cce-209baef361d9.png">

**Comment by gre** [comment]
I'm aware of this. The new 2.0.0 docs is breaking something on Gitbook website. I'm waiting to hear from @SamyPesse because I have no idea what's wrong in the new docs, and the error in Gitbook is not clear.

In the meantime you can open the https://github.com/ProjectSeptemberInc/gl-react/tree/master/docs folder.
If you are looking for 1.x docs, it's still available here: https://github.com/ProjectSeptemberInc/gl-react/tree/v1.2.5/docs

**Comment by macrostart** [comment]
Thanks for the quick reply! I'll leave this issue open for now, the links helped me and could be helpful to others.

**Comment by SamyPesse** [comment]
@gre The issue is coming from this line https://github.com/ProjectSeptemberInc/gl-react/blob/master/book.json#L3

Basically the latest version of GitBook don't accept structure files that are not in the root folder.

The solution is to use gitbook `2.5.2`, in your `book.json`, add:

```
{
     "gitbook": "2.5.2"
}
```

The next release of gitbook `2.7.0` will probably include an option `root` for people using something like a `docs` folder.

**Comment by gre** [comment]
@SamyPesse awesome! thanks. It works!

@marcoreat : Please continue reading the v1.2.5 doc on https://github.com/ProjectSeptemberInc/gl-react/tree/v1.2.5/docs . the v1.0.0 is not announced yet, and is likely to change a bit (currently working on integrating with Babel 6)

**Comment by macrostart** [comment]
Great to have this resolved, thanks!
