### ISSUE TITLE
resize in surface

### ISSUE THREAD

**Issue by genxstylez** [ProjectSeptemberInc/gl-react-native#62]
Hi,

I am trying to use the 4-pass blur on my app, and my image is being resize to the surface width and height but I want it to style like the `<Image>` component's `resizeMode: 'cover`

below is my code, please help.

``` js
<Surface width=400 height=600 preload>
    <Blur minBlur={0} maxBlur={3} blurMap={'http://i.imgur.com/0PkQEk1.png'} offset={[10, 0]}>
        http://cdn12.lbstatic.nu/files/looks/large/2015/12/30/4789931_deichmann-with-skirt.jpg?1451472058
    </Blur>
</Surface>
```

**Comment by gre** [comment]
In theory you could put an `<Image>` there instead of the URL

**Comment by gre** [comment]
but if you do this, you need to make sure you retrigger a render after the inner image loads (forceUpdate() or setState())

**Comment by gre** [comment]
like `<Image onLoad={() => this.forceUpdate()} resizeMode="cover" source={{ ... }} />`

**Comment by genxstylez** [comment]
it works! thanks!

**Comment by genxstylez** [comment]
Just found out if I put a Image with forceupdate onload and change the factor of the blur to retrigger render, the FPS drops drastically compare to without `<Image>`

any ideas on how to deal with it?

**Comment by gre** [comment]
there might be multiple ways to optimize this. The best way would be to profile using the "systrace" available from the debugging menu, and to see what's the bottleneck.

Here is some thoughts
- by giving an `<Image>`, gl-react-native will always have to rasterize again it because it doesn't know if the view has changed. This is why it's slower than just giving the image URL. That said, in some cases it could be faster, for instance if you have a huge image, `<Image>` will do the work to resize it. To optimize rasterization, I'm considering introducing a shouldUpdate prop on GL.Uniform so you can say if it gl-react-native should rasterize again or not. see https://github.com/ProjectSeptemberInc/gl-react/issues/27#issuecomment-174298635 
- more you have GL.Node in the graph, more it will takes time (it's ~ linear) because each Node result of a Framebuffer and a glDrawArrays call. In your case, having 4 passes of the blur is slower that if you could have 2.
- To compensate the need to use a lot of passes, you could try to use a smaller framebuffer size. To do this, try to use a small width and height on your Blur. Using a smaller size will make the shader faster AND will also contribute to the blur effect (pixel interpolation). For instance, in my own code I've moved from a `<Blur passes={4} width={400} height={400}>` to a `<Blur passes={2} width={64} height={64}>` and result was satisfying while gaining about 10x of perf.
- If it's possible, you might "step the sliders". I mean, that instead evolving the blur intensity from 0 to 2 in a continuous domain, you can try to step by 0.1 or 0.01 (e.g 0.0, 0.1, 0.2, ...).
- Finally, make sure the render() function of your component that renders the Surface don't get retriggered for no changes. each Surface#render() triggers a new GL rendering. You should implement shouldComponentUpdate. or alternatively use a StaticContainer.

**Comment by genxstylez** [comment]
> Finally, make sure the render() function of your component that renders the Surface don't get retriggered for no changes. each Surface#render() triggers a new GL rendering. You should implement shouldComponentUpdate. or alternatively use a StaticContainer.

What does it mean by retrigger? if the factor is in the state, and so the state change would intentionally retrigger a render, and that is by deisgn right? or are there alternative ways to change the factor?

**Comment by genxstylez** [comment]
> o compensate the need to use a lot of passes, you could try to use a smaller framebuffer size. To do this, try to use a small width and height on your Blur. Using a smaller size will make the shader faster AND will also contribute to the blur effect (pixel interpolation). For instance, in my own code I've moved from a <Blur passes={4} width={400} height={400}> to a <Blur passes={2} width={64} height={64}> and result was satisfying while gaining about 10x of perf.

Can't really do that, cos I am blurring the backgroundImage of the app, which is a full-width & height image

**Comment by gre** [comment]
Not sure if i'm clear, but when I say using a smaller size, I don't mean the surface size, I mean the GL.Node width and height.

``` js
<GLSurface width={1000} height={500}>
  <Blur width={64} height={64} />
</GLSurface>
```

there is a current limitation (https://github.com/ProjectSeptemberInc/gl-react/issues/33) that this won't work for the root node, but it will for all children

For "retrigger", I mean that you enter again in a render().
If you have some setState() / dispatch / forceUpdate in one of the parent, your component render() will be called again even if it's not an internal update. You can shortcut this with shouldComponentUpdate ( https://facebook.github.io/react/docs/component-specs.html#updating-shouldcomponentupdate ) to explicitely say when things need to be re-rendered.

**Comment by genxstylez** [comment]
@gre I get the shouldComponentUpdate part, but when I want to change the blur factor, I must re-render right?

**Comment by genxstylez** [comment]
@gre below is the code I m using, I don't think I can avoid the retriggering.

``` jsx

onScroll(e) {
    this.setState({ factor: e.content.offset.y})
},
render() {
url = 'http://cdn12.lbstatic.nu/files/looks/large/2015/12/30/4789931_deichmann-with-skirt.jpg';
<ScrollView onScroll={this.handleScroll}>
<Surface width=400 height=600 preload>
    <Blur factor={this.state.factor}>
        <Image source={{uri: url}} />
    </Blur>
</Surface>
</ScrollView>
}
```

also, What will happen if I explicitly lower the Blur Node's width and height? say `<Blur width=50, height=50>`

**Comment by gre** [comment]
by default Blur will use the parent size which is 400x600. If you decrease the size of the Blur GL.Node's, to let's say 200x300, it will be 4 times less pixel to process for the GPU. It will only rule the size of the intermediary framebuffers but not the last framebuffer (the Surface one)).
Also when the GPU will convert 200x300 to 400x600 it will do linearly (LINEAR pixel interpolation is used in framebuffers). So it's doing a linear blur for free, which will contribute to a better blur effect.

not sure what you can do for the onScroll, but maybe you can (1) throttle it and (2) step it (so you only setState when you move far enough from the old factor).

if it still don't help, I guess you'll need to wait we implement the issues I've mentioned: https://github.com/ProjectSeptemberInc/gl-react/issues/33 and https://github.com/ProjectSeptemberInc/gl-react/issues/27#issuecomment-174298635

**Comment by genxstylez** [comment]
@gre thx, I will give it a try and get back to u tmr

**Comment by genxstylez** [comment]
@gre 

> Also when the GPU will convert 200x300 to 400x600 it will do linearly (LINEAR pixel interpolation is used in framebuffers). So it's doing a linear blur for free, which will contribute to a better blur effect.

does that apply to 4-pass blur too?

**Comment by gre** [comment]
depends on Blur implementation, if it's gl-react-blur yes

**Comment by genxstylez** [comment]
gl-react-blur with 4-pass ?

**Comment by gre** [comment]
can you try to also constraint the width and height of the Image ? I think it get screenshot with a huge size.

<Surface width=400 height=600 preload>
    <Blur factor={this.state.factor} passes={4} width={200} height={300]>
        <Image source={{uri: url}} width={200} height={300] />
    </Blur>
</Surface>

the width/height has to be ajusted and tested to obtain the best blur and the best perf. you might want to try either passes=4 or see if passes=2 is acceptable there

**Comment by gre** [comment]
@genxstylez I've discovered a bug in gl-react-blur that was ignoring the width, height, pixelRatio you give to `<Blur/>`. I've released a minor version to fix it. sorry for this.

**Comment by genxstylez** [comment]
@gre nice to hear! will try it out

**Comment by gre** [comment]
@genxstylez #33 finally landed. It allows to scale the root node to the surface with a fast copy shader.

Example:

```
<Surface width={100} height={100}>
  <GL.Node width={2} height={2} />
</Surface>
```

will produces:

<img width="94" alt="screen shot 2016-02-16 at 11 52 01" src="https://cloud.githubusercontent.com/assets/211411/13110277/3aa846b8-d57f-11e5-992a-6ec91f13b3e4.png">

but NOT

<img width="94" src="https://cloud.githubusercontent.com/assets/211411/13110281/40bb6364-d57f-11e5-95c4-11834acacd73.png" />

(notice how the first image only have 4 pixels, but the color get interpolated. so it's perfect for blur)

Give a try to gl-react 2.2.0 and gl-react-native 2.20.0. should also have better perfs.

**Comment by genxstylez** [comment]
@gre thx! I will give it a try! does that apply to gl-react-blur too?

**Comment by gre** [comment]
yes.
you can try doing  for instance

```
<Surface width={400} height={400}>
  <Blur {...} width={40} height={40} />
</Surface>
```

**Comment by genxstylez** [comment]
@gre cool!
