### ISSUE TITLE
[iOS] Applying blur to a surface

### ISSUE THREAD

**Issue by pfeodrippe** [ProjectSeptemberInc/gl-react-native#74]
I'm trying to put a Surface component (with a GL node inside) in a Blur component (as described in one of the examples), but only the react-native components (Text, Views etc) are rendered while the shader in the GL node is not.

There is some workaround for this to work?

Thanks in advance!

**Comment by macrostart** [comment]
Gl-react's documentation [mentions](https://projectseptemberinc.gitbooks.io/gl-react/content/docs/api/Surface.html) that stacking shaders should be done via nesting multiple GL.Node elements under one Surface object. You can check the ["Simple" example](https://github.com/ProjectSeptemberInc/gl-react-native/blob/298ce6c488996ace82348a96e746b2881eeb5b1f/example/src/Simple/index.js#L243-L267) to see it in action .

Is your case different and you have to explicitly apply a shader to the Surface element?

**Comment by gre** [comment]
yes, you can't nest a Surface into a Surface, mainly by design but also by limitation of what iOS / Android allow to do (nor allow to snapshot a opengl view the same way we can for a normal View).

so same answer as in https://github.com/ProjectSeptemberInc/gl-react-native/issues/86 : 

Instead of doing:

``` html
<Surface>
   <...>
     <Surface>
       <A/>
     </Surface>
   </...>
</Surface>
```

you should be doing

``` html
<Surface>
   <...>
     <A/>
   </...>
</Surface>
```

and it would work.
