### ISSUE TITLE
Store shader code in seperate file

### ISSUE THREAD

**Issue by miklosme** [ProjectSeptemberInc/gl-react-native#83]
I just found a great GLSL plugin for my IDE, so it would be great, if I could store the shader code in a seperate `.glsl` file. Are there any know workarounds for this?

It seems like React Native Packager don't support something like Webpack's [raw loader](https://github.com/facebook/react-native/issues/7826).

**Comment by gre** [comment]
yes, I can't wait to have this feature.
We initially requested it here: https://github.com/facebook/react-native/issues/2328

it has been closed for inactivity. Unfortunately, I'm not sure there is any workaround if you still want the _.glsl_ extension, but feel free to upvote that react-native issue/on product pains.

I'm closing this, because it's not something we can solve in our library, but it has to be solved by react-native.
