### ISSUE TITLE
Animated Surface Container

### ISSUE THREAD

**Issue by sscaff1** [ProjectSeptemberInc/gl-react-native#84]
I have a wrapper component where the size and location of the view is animated for photo editing purposes (very similar to instagram). The problem that I'm having is that the child I typically pass into the component has a flexed style. Here is a typical example.

```
<PannableImage
  imageHeight={imageHeight}
  imageWidth={imageWidth}
>
  <Image source={imageSource} resizeMode="cover" style="{{ flex: 1 }}" />
</PannableImage>
```

The imageHeight and Width are just used to set the initial values of the view. After that, Animated values take over.

I'd like to be able to pass in a Surface into the component. The problem is that I can't flex a Surface, and it doesn't seem like I can pass the Surface animated height and width values. Panning actually works fine (because I'm panning the view around the surface), I'm just hung up the height and width. Anyone ever try something like this? Any suggestions?

EDIT: One more thing - the way the PannableImage works is that if the view is smaller than the containing view then the view will pop back up (i.e grow the height and width of the containing view). That's really why a flexed surface view would come in handy.

**Comment by gre** [comment]
you are right that `Surface` currently won't support `width` and `height` props to be animated objects, these must be integers at the moment. We can probably fix this using react-native `Animated.createAnimatedComponent` to make **[this code](https://github.com/ProjectSeptemberInc/gl-react-native/blob/master/src/GLCanvas.js#L107)** an _GLCanvasNativeAnimated_.
But we will also need to replace all usage of View by Animated.View [here](https://github.com/ProjectSeptemberInc/gl-react-native/blob/master/src/Surface.js#L40). So maybe, worth making some special **AnimatedSurface** if all of these works (i'm not sure if Animated is a big overhead, but it's probably still a better idea to have this special component, like Animated have also their special components Animated.View / Animated.Image / ...).

So this is a first problem that the library should support and i've created https://github.com/ProjectSeptemberInc/gl-react-native/issues/85 to track this.

Now back to your image use-case:
when dealing with images in `gl-react-native`, I recommend to use the "built-in" texture support, rather than using React Native Image component. Which means, instead of using a VDOM `<Image />` just passing it `imageSource` in the uniforms. This will be more efficient and you will be sure the Surface get redrawn when the image loads. if you still want to use React Native Image component, you have this nice feature of flex and resizeMode of course, but the downside is that Surface is totally blind that it's an Image (we don't treat it as an image, but just as a UIView, and we will rasterise it, also we can't wait for a onLoad event), so you will need to forceUpdate to trigger a re-render (or use autoRedraw prop, but it's overkill and not the most efficient idea^^).

**Comment by gre** [comment]
what I tend to recommend is to use `Image.getSize` to get the image dimension, and from that, doing some math to preserve the ratio (basically reimplement the resizeMode in a shader).

For **flex**-ing the Surface, it also seems to be an interesting idea, I need to test if this can work. I'm having some doubt around this as GLKView is a special thing. will also need to give a try.

**Comment by gre** [comment]
the main problem with all of this is that width and height is expected to be numbers a bit everywhere in the code, not only here but also in `gl-react`. Looks like this need an important refactoring.

**Comment by gre** [comment]
(well, i'm not even sure if width/height are actually even used as numbers in gl-react, they just get passed-in^^ so maybe it's ok )

**Comment by sscaff1** [comment]
> Which means, instead of using a VDOM <Image /> just passing it imageSource in the uniforms. This will be more efficient and you will be sure the Surface get redrawn when the image loads. if you still want to use React Native Image component, you have this nice feature of flex and resizeMode of course, but the downside is that Surface is totally blind that it's an Image (we don't treat it as an image, but just as a UIView, and we will rasterise it, also we can't wait for a onLoad event), so you will need to forceUpdate to trigger a re-render (or use autoRedraw prop, but it's overkill and not the most efficient idea^^).

@gre I'm currently do this.

PannableImage is also cloning the child that's passed to it so that it can pass it the correct height and width like below. I basically need to be able to Flex the surface or have the surface source be an Animated.View. Right now this.currentSizeValue is a listener on the animatedXY value. So the below works without animation but that's not really what I want. 

```
{React.cloneElement(
            React.Children.only(children), {
              imageWidth: this.currentSizeValue.x,
              imageHeight: this.currentSizeValue.y,
            }
          )}
```

**Comment by gre** [comment]
flex sounds hard to implement right now, but animated should be possible.

**Comment by sscaff1** [comment]
@gre I tried your suggestion above https://github.com/doubleqliq/gl-react-native/commit/15b140cf8ee7f3b93285942fe8535a3e813a47e3. 

The above does not seem to work though. I still get an unhandled promise rejection so it seems that this issue is a little more difficult. Thanks for the suggestion though.

**Comment by gre** [comment]
@sscaff1 I've released gl-react-native 2.26.1 and gl-react 2.2.2.

You can import `AnimatedSurface` that supports width and height props to be Animated objects.

``` js
import React, {Component} from "react";
import {View, Animated} from "react-native";
import {AnimatedSurface} from "gl-react-native";
import GL from "gl-react";

export default class AnimatedExample extends Component {
  state = {
    heightValue: new Animated.Value(200),
  };
  componentWillMount () {
    let i = 0;
    this.interval = setInterval(() =>
      Animated.spring(this.state.heightValue, {
        toValue: ++i % 2 ? 500 : 200,
      }).start(), 1000);
  }
  componentWillUnmount () {
    clearInterval(this.interval);
  }
  render () {
    const { heightValue } = this.state;
    return <View style={{ paddingTop: 60, alignItems: "center" }}>
      <AnimatedSurface
        width={200}
        height={heightValue}>
        <GL.Node shader={{// inline example
            frag: `
precision highp float;
varying vec2 uv;
void main () {
  gl_FragColor = vec4(uv.x, uv.y, 0.5, 1.0);
}
            `
          }}
        />
    </AnimatedSurface>
    </View>;
  }
}
```

**Comment by sscaff1** [comment]
@gre thank you so much!

**Comment by sscaff1** [comment]
@gre I can't seem to get this work. Basically I just keeping getting unhandled promise rejection from GL.Surface saying that the prop must be strictly positive number. I have the latest gl-react-native and gl-react installed. Here is my code:

```
  <AnimatedSurface
        ref={surface => this.myFilter = surface}
        style={style}
        width={width}
        height={height}
      >
    <GL.Node shader={shaders.hue} uniforms={{ factor }}>
      <GL.Uniform name="image">{children}</GL.Uniform>
    </GL.Node>
</AnimatedSurface>
```

width and height are animated values. Am I doing something wrong?

**Comment by sscaff1** [comment]
I'm actually doing 

```
export const Hue = GL.createComponent(
  ({ children, factor }) =>
    <GL.Node shader={shaders.hue} uniforms={{ factor }}>
      <GL.Uniform name="image">{children}</GL.Uniform>
    </GL.Node>
);
```

```
<AnimatedSurface
        ref={surface => this.myFilter = surface}
        style={style}
        width={width}
        height={height}
      >
   <Hue factor={10}>
            {children}
          </Hue>
</AnimatedSurface>
```

children is just an image URL

**Comment by sscaff1** [comment]
@gre It would have been nice if I would have restarted my packager. Thank you so much work for this. I can confirm that this works.
